name: Program Intake Template
description: Submit an intake form for a new program to be reviewed by [Engineering Program Management team](https://vault.shopify.io/teams/2621-Engineering-Program-Management-Office-of-CTO/)
labels: ["Ideas"]
body:
  - type: markdown
    attributes:
      value: |
        The fields below are used to populate a Program Brief. Please fill in as much detail as you can in order for the EPM team review and prioritize among other programs in the EPM backlog.
  - type: input
    id: program-name
    attributes:
      label: Program Name
      description: Please provide a Program Name. Avoid covert program names only understandable to those working on the initiative. Programs will be Vault projects or Missions to accommodate existing tooling. 
    validations:
      required: true
