name: Program Intake Template
description: Submit an intake form for a new program to be reviewed by [Engineering Program Management team](https://vault.shopify.io/teams/2621-Engineering-Program-Management-Office-of-CTO/)
labels: ["Ideas"]
body:
  - type: markdown
    attributes:
      value: |
        The fields below are used to populate a Program Brief. Please fill in as much detail as you can in order for the EPM team review and prioritize among other programs in the EPM backlog.
  - type: input
    id: program-name
    attributes:
      label: Program Name
      description: Please provide a Program Name. Avoid covert program names only understandable to those working on the initiative. Programs will be Vault projects or Missions to accommodate existing tooling. 
    validations:
      required: true
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What can our users or the company do after this goal is achieved? Why should we solve this problem now?
    validations:
      required: true
  - type: textarea
    id: key-stakeholders
    attributes:
      label: Key Stakeholders
      description: Who are the key stakeholders or main points of contact for this area?
    validations:
      required: true
  - type: textarea
    id: objectives
    attributes:
      label: Objectives
      description: When we’re done, what’s now possible? What can merchants, developers, and Shopify do after this goal is achieved?
    validations:
      required: true
  - type: textarea
    id: program-deps
    attributes:
      label: Dependencies
      description: Is there anything else that needs to be changed before this program can be started?
    validations:
      required: true
